### ISSUE TITLE
"libcsys-ruby version (0.6.1) doesn't match helix_runtime version (0.6.0)"

### ISSUE THREAD

**Issue by djudd** [tildeio/helix#101]
I get the following error when attempting to require a gem that was built with Helix on Linux (specifically Ubuntu trusty, 14.04.5):
```
irb(main):001:0> require 'humanname'
thread '<unnamed>' panicked at 'libcsys-ruby version (0.6.1) doesn't match helix_runtime version (0.6.0).', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libcruby-sys-0.6.1/src/lib.rs:15
```
The gem was built on Travis per [this .travis.yml](https://github.com/djudd/human-name-rb/blob/master/.travis.yml) and can be downloaded [from GitHub](https://github.com/djudd/human-name-rb/releases/download/0.4.3-pre1/humanname-0.4.3-x86_64-linux.gem).

(I tried checking in a Cargo.lock which includes both at 0.6.1 but it didn't help.)

**Comment by wagenet** [comment]
@djudd this means that the helix_runtime gem doesn't match the helix crate version. Try making sure the gem is 0.6.1.
