### ISSUE TITLE
Is there a way to implement a method on any object?

### ISSUE THREAD

**Issue by NullVoxPopuli** [tildeio/helix#106]
Here is an example in RuRu:
https://github.com/NullVoxPopuli/case_transform-rust-extensions/blob/30c7394562c07d0034b66e297a65dcf3fd718403/ext/case_transform/src/lib.rs#L80

Basically, it just allows passing of any type to a method, and you try converting to something until you get what you want.

Maybe there is a way to do this with Generics?

I know the implementation of each method I want per type -- just not sure how to go about it (String, Symbol, Array, and Hash)

**Comment by chancancode** [comment]
I believe this is now possible – see the new json_builder example I added in #128. Feel free to reopen if that doesn't work for some reason!
