### ISSUE TITLE
Unable to use the return type Vec<[f64; 2]>

### ISSUE THREAD

**Issue by nathanpalmer** [tildeio/helix#111]
I'm looking to interop with a rust library for decoding polylines. It however returns a type of `Vec<[f64; 2]>` which seems to be an unsupported conversion.

```rust
#[macro_use]
extern crate helix;
extern crate polyline;

ruby! {
    class Polyline {
        def decode_polyline(text: String) -> Vec<[f64; 2]> {
            polyline::decode_polyline(text, 5).unwrap();
        }
    }
}
```

Which during the build step gives me this

```
error[E0277]: the trait bound `std::vec::Vec<[f64; 2]>: helix::ToRuby` is not satisfied
  --> src/lib.rs:5:1
   |
5  |   ruby! {
   |  _^ starting here...
6  | |     class Polyline {
7  | |         def decode_polyline(text: String) -> Vec<[f64; 2]> {
8  | |             polyline::decode_polyline(text, 5).unwrap();
9  | |         }
10 | |     }
11 | | }
   | |_^ ...ending here: the trait `helix::ToRuby` is not implemented for `std::vec::Vec<[f64; 2]>`
   |
   = note: required by `helix::ToRuby::to_ruby`
   = note: this error originates in a macro outside of the current crate
```

According to [the documentation](https://docs.rs/polyline/0.4.0/polyline/fn.decode_polyline.html) the function definition seems correct. However, is there a way to define new coercions or possibly another way to approach this?

Though #46 might be a blocker here as well.

**Comment by wagenet** [comment]
@nathanpalmer I think you're correct that the issue is that we don't have proper conversions for the array. One workaround might be to change the format before you return it. I'm hoping to find some time to allocate to this stuff soon :/

**Comment by chancancode** [comment]
I believe this is now possible since #126. Let me know if that works for you.

By the way, would coercion for tuples be helpful to you here? Curious why you went with `Vec<[f64; 2]>` as opposed to `(f64, f64)`
