### ISSUE TITLE
rake build doesn't fail if the crate fails to compile

### ISSUE THREAD

**Issue by DRMacIver** [tildeio/helix#133]
When running "rake build" it exits with a zero status even if compiling the underlying crate failed.

As far as I can tell this is by design (or at least the code doesn't seem to attempt to do otherwise), but it makes the rake task quite hard to rely on because e.g. if there's a previously built version of the library then when running tests it will try to build, fail, and happily continue running against the old version.

**Comment by chancancode** [comment]
This is definitely a bug! Fixing it in #151
