### ISSUE TITLE
Build task fails with crates from git repositories

### ISSUE THREAD

**Issue by paukul** [tildeio/helix#140]
Adding a crate that's in a git repository leads to the following error during the build rake task (using rayon as an example since it's in one of the examples from the helix repository so it should, theoretically, work):

```
Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 10 char 1.
`- Don't know what to do with "rayon" at line 10 char 1.
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/helix_runtime-0.6.4/lib/helix_runtime/project.rb:28:in `name'
/usr/local/lib/ruby/gems/2.4.0/gems/helix_runtime-0.6.4/lib/helix_runtime/build_task.rb:62:in `define'
/usr/local/lib/ruby/gems/2.4.0/gems/helix_runtime-0.6.4/lib/helix_runtime/build_task.rb:33:in `initialize'
/Users/paukul/code/njiuko/zebroid/lib/tasks/helix_runtime.rake:3:in `new'
/Users/paukul/code/njiuko/zebroid/lib/tasks/helix_runtime.rake:3:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

the corresponding dependencies section in Cargo.toml is

```
[dependencies]
rayon = { git = "https://github.com/nikomatsakis/rayon" }
helix = "0.7.2"
```

is this a bug or am i just plainly doing something wrong?

**Comment by chancancode** [comment]
@paukul it seems like the error is happening because `Tomlrb.load_file(cargo_toml_path)["package"]["name"]` failed with calling `[]` on `nil`, presumably because `Tomlrb.load_file(cargo_toml_path)["package"]` returned `nil`. Do you not have a `package` section in your `Cargo.toml` or perhaps adding the git dependency causes `Tomlrb` to parse it incorrectly?

**Comment by paukul** [comment]
your comment actually hinted me into the right direction, thanks.
When trying to reproduce this error I realized that Tomlrb was not used. It was using TOML instead. Looks like I was using an oldish example where the gemspec had listed a dependency to `'helix_runtime', '~0.6.0'`. Upgrading it to `~0.7.2` fixed it. Thanks and sorry for opening up an issue before exhausting all options on my side
