### ISSUE TITLE
Classes require cloneable fields

### ISSUE THREAD

**Issue by DRMacIver** [tildeio/helix#143]
I'm currently trying to use Helix to wrap a Rust object that does not implement `Clone`, but it appears that Helix classes are automatically set up to derive Clone.

For example, given the following (not my real example, but vaguely derived from it)

```rust
use std::sync::mpsc::{sync_channel, SyncSender, Receiver};

ruby! {
  class ChannelWrapper {
    struct {
      sender: SyncSender<()>,
      receiver: Receiver<()>,
    }

    def initialize(helix){
      let (a, b) = sync_channel(1);
      ChannelWrapper{helix, sender: a, receiver: b}
    }
  }
```

This will fail with:

```
   the trait `std::clone::Clone` is not implemented for `std::sync::mpsc::Receiver<()>`
   note: required by `std::clone::Clone::clone`
```

I had a look through the helix source and I couldn't come up with a reason why these needed to be `Clone`, and it seems to work when I just implement `clone()` to panic (which is my workaround for now). Could the restriction be lifted?

**Comment by chancancode** [comment]
Yeah, I consider this a bug. There are some cloning related things I would like to fix, so I'll add this to the list.
