### ISSUE TITLE
release helix_runtime as a gem to rubygems?

### ISSUE THREAD

**Issue by NullVoxPopuli** [tildeio/helix#21]
I know this is still an early project, but for testing things out, it would be super helpful, if we didn't need to muck around with installing helix_runtime from source in our own gems.

/cc @chancancode

**Comment by wagenet** [comment]
@NullVoxPopuli see the examples in the `duration_wip_windows` branch. You should be able to set up a `Gemfile` and `Cargo.toml` to point at this repo on Github and it should all work. (On Windows there may be a couple of additional steps.)

**Comment by wagenet** [comment]
See also https://github.com/hone/helix-console
