### ISSUE TITLE
Active project?

### ISSUE THREAD

**Issue by pschambacher** [tildeio/helix#22]
Hi!

I'm extremely interested in this project and it would be awesome to see it feature complete.
I'd like to help but although I'm pretty fluent in Ruby, my C is extremely bad and rusty (pun almost intended) and I'm pretty new to rust. Is there still a way that I could contribute?
Is the project still active? The last commit goes back to June...

**Comment by ZhangHanDong** [comment]
I also want to ask this question.

**Comment by iamthemuffinman** [comment]
Judging that any of the core maintainers haven't responded yet, I'd guess no. @pschambacher You might look at [ruru](https://github.com/d-unseductable/ruru) as a substitute.

**Comment by ZhangHanDong** [comment]
Thanks @iamthemuffinman 

I have followed ruru ，Are there any differences between them?

**Comment by wagenet** [comment]
It's active again :)
