### ISSUE TITLE
error running tests in duration_wip branch with turbo_blank on linux

### ISSUE THREAD

**Issue by hone** [tildeio/helix#28]
I'm trying to run `bundle exec rake test` and am seeing

```
error: no rules expected the token `self`
 --> src/lib.rs:6:22
  |
6 |         def is_blank(self) -> bool {
  |                      ^^^^

error: Could not compile `turbo_blank`.
```

**Comment by chancancode** [comment]
actually, I know what's up; we broke the reopen macros on the branch atm (which is why I haven't merged it yet), so only `Console` works. (`Duration` works too, but the tests are bogus)

**Comment by wagenet** [comment]
Was fixed a while ago :)
