### ISSUE TITLE
Improve Windows Scripting

### ISSUE THREAD

**Issue by chancancode** [tildeio/helix#34]
@wagenet did a great job with #29; it's great for now.

Before shipping 1.0, we should review the PR again to see if there are any ways to simplify the way it works. @wagenet: would you mind jotting down any ideas you have for future improvements here?

**Comment by wagenet** [comment]
The main question right now is whether there's a way we can avoid having to copy the helix-runtime.dll into the Windows $PATH. It would certainly be nice not to have to do that.

Also, it would be nice to be able to do full gem releases on a single *nix system. However, the current setup requires the use of `lib.exe` from Visual Studio to create a `helix-runtime.lib`. I don't know that we can replicate this on non-Windows machines.

**Comment by hone** [comment]
is there a way to create `helix-runtime.lib` with `mingw`?

**Comment by wagenet** [comment]
@hone no, we generate a `.def` file and need to turn that into a `.lib`. I am not aware of how to create a `.lib` without `lib.exe`.

**Comment by wagenet** [comment]
@hone ah, `dlltool` may be able to do it.

**Comment by wagenet** [comment]
I think we've probably done enough for now. Not sure that we need this open anymore. If we have any more specific ideas we can make a new ticket.
