### ISSUE TITLE
Unable to sucessfully build examples (calculator, turbo_blank)

### ISSUE THREAD

**Issue by flajann2** [tildeio/helix#69]
I am on Ubuntu 16.04
using Ruby 2.4.1p111 and Rust 1.16.0
and bundler 1.14.6.

I followed the README.md on Running the examples, then cded into the calculator directory, and ran:

bundle install
bundle exec rake

And wound up with macro failures:

-----
$ bundle exec rake build

Building helix runtime

bundle exec rake compile:native

Runtime built

{"HELIX_LIB_DIR"=>"/development/rust_proj/helix/ruby/windows_build"}
cargo rustc --release -- -C link-args=-Wl,-undefined,dynamic_lookup
   Compiling helix_runtime v0.5.0-alpha-3 (file:///development/rust_proj/helix)
error: expected identifier, found keyword `pub`
   --> /development/rust_proj/helix/src/macros/parser.rs:123:19
    |
123 |             pub: $pub:tt,
    |                   ^^^

error: expected identifier, found keyword `pub`
   --> /development/rust_proj/helix/src/macros/parser.rs:132:23
    |
132 |                 pub: $pub,
    |                       ^^^

error: expected identifier, found keyword `pub`
   --> /development/rust_proj/helix/src/macros/parser.rs:143:19
    |
143 |             pub: $pub:tt,
    |                   ^^^
...
error: aborting due to 70 previous errors

error: Could not compile `helix_runtime`.

To learn more, run the command again with --verbose.
rake aborted!
native source doesn't exist, run `cargo_build` first; source=/development/rust_proj/helix/target/release/libturbo_blank.so
/development/rust_proj/helix/ruby/lib/helix_runtime/project.rb:109:in `copy_native'
/development/rust_proj/helix/ruby/lib/helix_runtime/project.rb:116:in `build'
/development/rust_proj/helix/ruby/lib/helix_runtime/build_task.rb:65:in `block in define'
/home/alveric/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/home/alveric/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)

-----

I am new to Rust, but have been doing Ruby development (and a number of other languages) for years. It appears I've missed a critical step for the macro installation, but I missed this step in the docs.

I am looking to incorporate Helix support in Jeweler in order to promote  doing Ruby gems in Rust. Any help here would be greatly appreciated. Also, a full step-by.step example of creating a Ruby gem with Rust would be cool, but I think I can get there once I can get the examples working!!!!

Thanks.

**Comment by chancancode** [comment]
@flajann2 currently, after landing #68 the new macros require rust beta until the fixes land in stable in a few weeks. So you would need to do `rustup override set beta` at the root as a workaround for now

**Comment by flajann2** [comment]
Wow, that did it! Thanks for the rapid turn-around time!
