### ISSUE TITLE
Any plans to make helix language-generic?

### ISSUE THREAD

**Issue by beamspease** [tildeio/helix#77]
I skimmed the source and it looks like you could probably reuse a great deal of the code for Python. Are there any plans to expand Helix to have the capability of generating other languages' libraries?

**Comment by wagenet** [comment]
@beamspease there aren't any plans yet since none of us are Python developers. That said, I definitely don't think we'd be opposed to extracting out a "helix-core" if it could be shared between other language-specific implementations.

**Comment by beamspease** [comment]
If it's not too hard to implement a new language, and if the Ruby implementation would be a good reference implementation, I think it'd be extraordinarily useful.

Rust is highly optimizable, but also has a steep learning curve. Being able to automatically generate an API for Python, Javascript, Golang, C++, etc would be huge even if there are caveats and restrictions applied to the structs / functions exported via a method. 

This seems like it could significantly aid adoption of Rust itself in two ways:
1) One person or a small number of people know Rust, and are producing high-performance or high-security code for a larger group of users working at a high level.
2) A codebase is being progressively moved to Rust. Parts of the non-Rust code can simply be removed once the Rust implementation is complete.

API wrappers for each language just doesn't scale very well. I'd like to have a C/++ and Python API for code that I'm writing, for instance, but I just haven't gotten around to writing wrapper functions for both and testing them. This looks like it would reduce that work to adding ~4 lines of code (python! { cpp! { ... } }) per file and seeing if it compiled.

**Comment by wagenet** [comment]
@beamspease there's definitely a good bit of work in implementing a new language since you have to tie into all of the existing language APIs. This isn't something that we're likely to ever tackle as a team. If you (or anyone else) does decide you'd like to do that work, let us know and we'd be happy to share what we've learned and see if there's any code we could share.
