### ISSUE TITLE
windows build not finding helix_runtime

### ISSUE THREAD

**Issue by dsisnero** [tildeio/helix#84]
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601

c:\Dominic\programming\rails\flipper>gem list helix

*** LOCAL GEMS ***

helix-rails (0.5.0)
helix_runtime (0.5.0)

c:\Dominic\programming\rails\flipper>rake build
Unable to load text_transform/native. Please run `rake build`
Building text_transform
rake aborted!
HelixRuntime::MissingDllError: Unable to find helix-runtime-0-5-0.dll in $PATH.

**Comment by wagenet** [comment]
@dsisnero is this the only message you see? There should also be a message saying: "Run `rake helix:copy_dll` to copy to your Ruby bin dir."

See https://github.com/tildeio/helix/blob/master/ruby/lib/helix_runtime/build_task.rb#L47

**Comment by dsisnero** [comment]
c:\Dominic\programming\rails\flipper\crates\text_transform>rake helix:copy_dll --trace
** Invoke helix:copy_dll (first_time)
** Execute helix:copy_dll
rake aborted!
Unable to find native bundle at c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/helix_runtime-0.5.0/lib/native.so
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/helix_runtime-0.5.0/lib/helix_runtime.rb:44:in `copy_dll'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/helix_runtime-0.5.0/lib/helix_runtime/build_task.rb:52:in `block in define'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
c:/Dominic/rubies/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
c:/Dominic/rubies/Ruby23-x64/bin/rake:22:in `load'
c:/Dominic/rubies/Ruby23-x64/bin/rake:22:in `<main>'
Tasks: TOP => helix:copy_dll

**Comment by wagenet** [comment]
@dsisnero hmm... doesn't seem good! We'll have to investigate more.

**Comment by wagenet** [comment]
@dsisnero Looks like 0.5.0 was a bad build for Windows. I've just released 0.6.0. Can you tell me if that fixes the issue?

**Comment by dsisnero** [comment]
c:\Dominic\programming\rails\flipper\crates\text_transform>bundle list
Gems included by the bundle:
  * bundler (1.14.6)
  * helix_runtime (0.6.0)
  * rake (12.0.0)
  * text_transform (1.0.0)
  * thor (0.19.4)

c:\Dominic\programming\rails\flipper\crates\text_transform>rake helix:copy_dll --trace
** Invoke helix:copy_dll (first_time)
** Execute helix:copy_dll
rake aborted!
Unable to find native bundle at c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/helix_runtime-0.6.0/lib/native.so
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/helix_runtime-0.6.0/lib/helix_runtime.rb:49:in `copy_dll'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/helix_runtime-0.6.0/lib/helix_runtime/build_task.rb:52:in `block in define'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
c:/Dominic/rubies/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
c:/Dominic/rubies/Ruby23/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
c:/Dominic/rubies/Ruby23/bin/rake:22:in `load'
c:/Dominic/rubies/Ruby23/bin/rake:22:in `<main>'
Tasks: TOP => helix:copy_dll

**Comment by wagenet** [comment]
@dsisnero darn, doesn't look like it is resolved yet. I'll have to investigate more. Sorry!

**Comment by wagenet** [comment]
@dsisnero @germolinal Should be fixed by 0.6.1. Let me know how it goes.
