### ISSUE TITLE
"No implicit conversion" message is misleading

### ISSUE THREAD

**Issue by alyssais** [tildeio/helix#85]
When I have a Helix class like this:

```rust
ruby! {
    class Thing {
        struct {
            a_string: String
        }

        def initialize(helix, a_string: String) {
            Thing { helix, a_string }
        }
    }
}
```

If I try to pass a non-`String` object into this class from Ruby, I get an error message:

```ruby
Thing.new(Object.new)
```

<blockquote><samp>
TYPE ERROR: "No implicit conversion of #&lt;Object:0x007f88920cc688&gt; into String"
</samp></blockquote>

So far, so good.

But, <q><samp>No implicit conversion of […] into String</samp></q> suggests to me that if I pass an object that _is_ implicitly convertible to a String, the implicit conversion will be performed. So let's try that:

```ruby
class TestString
  def initialize(string)
    @string = string
  end

  def to_str
    @string
  end
end

Thing.new(TestString.new("hello world"))
```

I get the same error, <q><samp>No implicit conversion of […] into String</samp></q>, even though I've defined an implicit conversion!

I think that either this message should be rephrased, or (preferably) Helix should attempt to use Ruby's implicit conversion protocols to convert arguments to Rust types, just like Ruby itself does.

**Comment by wagenet** [comment]
You're right that we can probably improve the handling of these cases. In the short term at least, we should probably change it to "no implicit conversion into Rust String". There is an implicit conversion, just not to a Ruby type.

**Comment by wycats** [comment]
I don't love using the term "Rust string" in the output. I'd prefer to explain the rules that caused the failure. Let me try to whip up a PR.
