### ISSUE TITLE
We need tests

### ISSUE THREAD

**Issue by flo-l** [tildeio/helix#9]
Tests are definitely necessary for this repo, IMHO.

I'm not sure how to go about this, as it's currently not possible to run scripts as tests, [see here](https://github.com/rust-lang/cargo/issues/1581).

But what about some ruby tests, rspec maybe? We need to test if the results on the ruby side are correct anyway ;)

**Comment by flo-l** [comment]
OK I just discovered the original branch, which includes rspec tests.

@wycats could you merge original and master?

**Comment by wycats** [comment]
@flo-l sorry about that and how long it has taken me to reply (I've been travelling for a bit!)

Yes, I think we should merge the branches and make sure we have a good testing setup that we can use with Travis.

**Comment by wagenet** [comment]
The `duration_wip` branch has Travis support.
