### ISSUE TITLE
Building gems on Windows?

### ISSUE THREAD

**Issue by germolinal** [tildeio/helix#94]
Hello, 

I use Ruby quite a lot, but exclusively for scripting and without Rails (I use it for scripting scientific computing and calling other programs)... so I basically know nothing about Rails and all its conventions.

Is it possible to build a gem using Helix without all the rails part? I started a new rust project, added the Helix crate, and when running 'cargo build' it obviously tells me that 'helix-runtime-0.6.0' must exist.

I understand this file is generated when 'bundle install' is executed on a gem... how can I generate it in my case?

THANKS IN ADVANCE!

**Comment by wagenet** [comment]
Helix doesn't have any requirement on Rails, so it should work fine for you. you should start by creating a `Gemfile` with helix in it. Then run `bundle install` and `bundle exec helix bootstrap .`. That will create the setup you need. After that, you should be able to build with `bundle exec rake build`.

**Comment by germolinal** [comment]
Wow, that was quick! Thanks very much!

I managed to move a bit forward, thanks. I did what you said: defined Helix as a dependency, ran `bundle install` (after a long while of fixing the Ruby DevKit), `bundle exec helix bootstrap .`, and when running `bundle exec rake build` I got the following error:

```
Unable to find helix-runtime-0-6-0.dll in $PATH
run rake helix:copy_dll to copy....
```

which I did, and I got:

```
Unable to find native bundle at C:/Ruby23-x64/lib/ruby/gems/helix_runtime-0.6.0/lib/native.so
```
and I noticed it was located on C:/Ruby23-x64/lib/ruby/gems/helix_runtime-0.6.0/lib/ **helix_runtime/** native.so 

I copied and pasted and everything seemed to be fine! until I 
```
bundle exec rake build
```
and I got, again, 
```
glare 1.0.0 built to pkg/glare-1.0.0.gem.
{}
cargo rustc --release
   Compiling libcruby-sys v0.6.0
error: failed to run custom build command for `libcruby-sys v0.6.0`
process didn't exit successfully: `C:\Users\German\Documents\glare\target\release\build\libcruby-sys-d19516c8797e1d79\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'helix-runtime-0-6-0.x86_64.lib must exist when running. Set HELIX_LIB_DIR to ruby/windows_build for development.', C:\Users\German\.cargo\registry\src\github.co
m-1ecc6299db9ec823\libcruby-sys-0.6.0\build.rs:29
note: Run with `RUST_BACKTRACE=1` for a backtrace.

rake aborted!
native source doesn't exist, run `cargo_build` first; source=C:/Users/German/Documents/glare/target/release/glare.dll

Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by wagenet** [comment]
@germolinal dang, sorry about this! Didn't realize you were on Windows. Looks like probably another case of #84. The good news is that it is possible to get it to work (we run CI on Windows), I just have to figure out why it isn't working out of the box.

**Comment by germolinal** [comment]
Thanks a lot! I will wait.... anxiously, haha.

Best,

**Comment by chancancode** [comment]
Closing as a dup of #84, but this is definitely something we're actively investigating.
