### ISSUE TITLE
Failure to build fresh install

### ISSUE THREAD

**Issue by KMarshland** [tildeio/helix#98]
I'm trying to follow the getting started tutorial, but I'm having issues.

I first run `rails generate helix:crate text_transform`, which executes fine. Next, I run `rake irb`, which tells me "Unable to load text_transform/native. Please run `rake build`" then aborts the rake task. When I run `rake build` though, it throws further errors, saying "error: aborting due to 70 previous errors error: Could not compile `helix`." [Full error messages here](https://github.com/tildeio/helix/files/1006614/logs.txt). As part of that, it recommends that I run `cargo build`. This provides 
[the same error messages](https://github.com/tildeio/helix/files/1006617/logs.txt)

I'm running Sierra v10.12.3, ruby 2.3.0p0, Rails 5.0.2, cargo 0.13.0-nightly, and rustc 1.12.0-nightly

**Comment by KMarshland** [comment]
Problem was solved by updating the Rust compiler. Note that `rustup update` failed to update it -- I had to uninstall and reinstall rust entirely to get it to update. It might be worth making a note about the required rust version in the readme.

**Comment by wagenet** [comment]
@KMarshland I've added a compatibility section to the README. Sorry for the trouble!
